server:
  port: 8082
spring:
  application:
    name: prover-domes
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/shool
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: {stat,wall,log4j}
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybaitis/mapper/*.xml
  type-aliases-package: com.example.priverd01.pojo
eureka:
  instance:
    prefer-ip-address: true
    instance-id: proder:8082
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
info:
  rediss: 湖南省株洲市
  name: 李孝红
